name: twins_front
description: "twins app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/twins_logo.png
